services:
  db:
    image: postgres:16-alpine
    container_name: labcheck-db
    environment:
      POSTGRES_USER: labcheck
      POSTGRES_PASSWORD: labcheck_dev
      POSTGRES_DB: labcheck
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
